/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence */
        get: operations["evidence_api_evidence__evidence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Examples
         * @description Example searches for the landing page, from the data being served.
         */
        get: operations["examples_api_examples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lookup Parcels
         * @description Parcels matching a county ID (dashed, compact or partial), block-lot or address.
         */
        get: operations["lookup_parcels_api_lookup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/map/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Map Features
         * @description Transit stops, parks, schools and neighborhood outlines (EPSG:4326).
         */
        get: operations["map_features_api_map_features_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/map/parcels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Map Parcels
         * @description Every parcel's geometry (EPSG:4326) with its band and score. Ranks arrive with search.
         */
        get: operations["map_parcels_api_map_parcels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/neighborhoods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Neighborhoods
         * @description The city's 90 neighborhoods, with how many candidates each has in the data.
         */
        get: operations["neighborhoods_api_neighborhoods_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parcels/{parcel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Parcel Report
         * @description Report header, the engine's analysis, and where its facts came from, by county ID.
         */
        get: operations["parcel_report_api_parcels__parcel_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Parcels
         * @description Candidates that pass every filter, ranked; near misses and a suggestion when empty.
         */
        post: operations["search_parcels_api_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Text
         * @description Plain-language description to search filters. It never searches, scores or ranks.
         */
        post: operations["parse_text_api_search_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Assembly */
        Assembly: {
            /** Assembly Id */
            assembly_id: string;
            /** Parcel Ids */
            parcel_ids: string[];
        };
        /** Assumption */
        Assumption: {
            /** Editable */
            editable: boolean;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Max */
            max: number | null;
            /** Min */
            min: number | null;
            /** Source */
            source: string;
            /** Unit */
            unit: string;
            /** Value */
            value: number;
        };
        /** Case */
        Case: {
            /** Case Id */
            case_id: string;
            /** Months To Decision */
            months_to_decision?: number | null;
            /** Neighborhood */
            neighborhood: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "granted" | "denied" | "withdrawn" | "pending";
            /** Request */
            request: string;
            /** Source Url */
            source_url?: string | null;
        };
        /**
         * CheckResult
         * @description One zoning rule applied to one building. Rules pass or fail; probability enters only
         *     through the approval (`relief_type`) that can fix a failure.
         */
        CheckResult: {
            /** Check Id */
            check_id: string;
            /** Label */
            label: string;
            /** Note */
            note: string | null;
            /** Provided */
            provided: number | null;
            /** Relief Type */
            relief_type: string | null;
            /** Required */
            required: number | null;
            /** Section */
            section: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "needs_approval" | "rejected" | "not_applicable";
            /** Unit */
            unit: string | null;
        };
        /** CodeReference */
        CodeReference: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Section */
            section: string;
            /** Summary */
            summary: string;
            /** Url */
            url?: string | null;
        };
        /** Comps */
        Comps: {
            /** Count */
            count: number;
            /** Radius Mi */
            radius_mi: number;
            /** Window Months */
            window_months: number;
        };
        /** CostRange */
        CostRange: {
            /** Drivers */
            drivers: string[];
            /** High */
            high: number;
            /** Low */
            low: number;
        };
        /** Evidence */
        Evidence: {
            /** As Of */
            as_of: string | null;
            /** Code Section */
            code_section: string | null;
            /** Layer */
            layer: string | null;
            /** Source */
            source: string;
            /** Url */
            url: string | null;
        };
        /** EvidenceDetail */
        EvidenceDetail: {
            /**
             * Ai Extracted
             * @default false
             */
            ai_extracted: boolean;
            /** Applies To */
            applies_to: string;
            /** Cases */
            cases?: components["schemas"]["Case"][];
            code?: components["schemas"]["CodeReference"] | null;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Confidence Note */
            confidence_note: string;
            /** How To Resolve */
            how_to_resolve: string;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "zoning_relief" | "physical" | "infrastructure" | "market";
            /** Median Months */
            median_months?: number | null;
            /** Precedent Granted */
            precedent_granted?: number | null;
            /** Precedent Total */
            precedent_total?: number | null;
            /** Title */
            title: string;
        };
        /**
         * Examples
         * @description Example searches for the landing page, taken from the data being served.
         */
        Examples: {
            /** Address */
            address: string;
            /**
             * Parcel Id
             * @description A partial county ID, dashed
             */
            parcel_id: string;
            /** Prompt */
            prompt: string;
        };
        /**
         * FilterChip
         * @description One active filter as the UI shows it. `key` says what removing the chip resets.
         */
        FilterChip: {
            /**
             * Key
             * @description SearchFilters field, or near:<feature> / constraint:<name>
             */
            key: string;
            /** Label */
            label: string;
        };
        /** Flag */
        Flag: {
            /**
             * Category
             * @enum {string}
             */
            category: "zoning" | "physical" | "environmental" | "infrastructure" | "market";
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Cost Usd */
            cost_usd: [
                number,
                number
            ] | null;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Id */
            id: string;
            /** Months */
            months: [
                number,
                number
            ] | null;
            /** Resolution */
            resolution: string;
            /** Resolved By Step */
            resolved_by_step: number | null;
            /**
             * Severity
             * @enum {string}
             */
            severity: "high" | "medium" | "low" | "unknown";
            /** Title */
            title: string;
        };
        /**
         * Freshness
         * @description Where the report's facts came from: the stored copy, or live lookups at report time.
         */
        Freshness: {
            /**
             * Fell Back
             * @description Layers whose live lookup failed, so the stored copy was used
             */
            fell_back: string[];
            /**
             * Live
             * @description Layers fetched live for this report
             */
            live: string[];
            /**
             * Live At
             * @description When the latest live lookup ran
             */
            live_at: string | null;
            /**
             * Parcels As Of
             * @description As-of date of the parcel records
             */
            parcels_as_of: string | null;
        };
        /** Gap */
        Gap: {
            /** High */
            high: number;
            /** Low */
            low: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Illustrative
             * @description True when any served parcel is mock data
             */
            illustrative: boolean;
            /** Parcels */
            parcels: number;
            /**
             * Site Source
             * @enum {string}
             */
            site_source: "mock" | "pipeline";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            versions: components["schemas"]["Versions"];
        };
        /** LandBasis */
        LandBasis: {
            /** Source */
            source: string;
            /** Value */
            value: number;
        };
        /**
         * LeadOption
         * @description The engine's headline program (`metrics.option`), for lists and the inspector card.
         */
        LeadOption: {
            /**
             * Label
             * @enum {string}
             */
            label: "by_right" | "with_relief";
            /** @description Margin on cost, as a fraction */
            margin?: components["schemas"]["Range"] | null;
            /**
             * Product Type
             * @enum {string}
             */
            product_type: "single_family" | "duplex" | "triplex" | "townhome" | "walkup";
            /**
             * Relief
             * @description Empty = by right
             */
            relief: string[];
            /** Units */
            units: number;
        };
        /** LookupMatch */
        LookupMatch: {
            /**
             * Matched On
             * @enum {string}
             */
            matched_on: "county_id" | "block_lot" | "address";
            parcel: components["schemas"]["ParcelSummary"];
        };
        /**
         * LookupResponse
         * @description What the search box detected, and the parcels it matches (IDs and addresses only).
         */
        LookupResponse: {
            /**
             * Format
             * @description For parcel IDs: county ID or city block-lot
             */
            format?: ("county" | "block_lot") | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "parcel_id" | "address" | "description" | "empty";
            /** Matches */
            matches: components["schemas"]["LookupMatch"][];
        };
        /** LotDimensions */
        LotDimensions: {
            /** Depth */
            depth: number;
            /** Width */
            width: number;
        };
        /** MapFeature */
        MapFeature: {
            /**
             * Geometry
             * @description GeoJSON geometry, EPSG:4326
             */
            geometry: {
                [key: string]: unknown;
            };
            properties: components["schemas"]["MapFeatureProperties"];
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
        };
        /** MapFeatureCollection */
        MapFeatureCollection: {
            /** Features */
            features: components["schemas"]["MapFeature"][];
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
        };
        /** MapFeatureProperties */
        MapFeatureProperties: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "transit_stop" | "park" | "school" | "neighborhood";
            /** Name */
            name?: string | null;
        };
        /**
         * Metrics
         * @description Headline numbers for the leading option (`option`).
         */
        Metrics: {
            approval_prob: components["schemas"]["Range"];
            comps: components["schemas"]["Comps"];
            land_basis: components["schemas"]["LandBasis"];
            land_over_max: components["schemas"]["Gap"] | null;
            max_land_price: components["schemas"]["Range"];
            months_to_permit: components["schemas"]["Range"];
            /**
             * Option
             * @enum {string}
             */
            option: "by_right" | "with_relief";
            site_cost_premium: components["schemas"]["CostRange"];
        };
        /** Narrative */
        Narrative: {
            /** Summary */
            summary: string | null;
        };
        /** NearFilter */
        NearFilter: {
            /**
             * Feature
             * @enum {string}
             */
            feature: "transit_stop" | "park" | "school" | "grocery";
            /**
             * Within Ft
             * @description Default: a quarter mile
             * @default 1320
             */
            within_ft: number;
        };
        /**
         * NearMiss
         * @description A candidate that fails exactly one active filter.
         */
        NearMiss: {
            failed: components["schemas"]["FilterChip"];
            parcel: components["schemas"]["ParcelSummary"];
        };
        /** Neighborhood */
        Neighborhood: {
            /**
             * Candidates
             * @description Development candidates with data in this neighborhood
             */
            candidates: number;
            /** Name */
            name: string;
        };
        /** NotChecked */
        NotChecked: {
            /** Label */
            label: string;
            /** Reason */
            reason: string;
            /** Section */
            section: string;
        };
        /** ParcelFeature */
        ParcelFeature: {
            /**
             * Geometry
             * @description GeoJSON geometry, EPSG:4326
             */
            geometry: {
                [key: string]: unknown;
            };
            properties: components["schemas"]["ParcelProperties"];
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
        };
        /** ParcelFeatureCollection */
        ParcelFeatureCollection: {
            /** Features */
            features: components["schemas"]["ParcelFeature"][];
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
        };
        /** ParcelProperties */
        ParcelProperties: {
            /** Assembly Id */
            assembly_id?: string | null;
            /** Band */
            band: ("fast_track" | "feasible_with_conditions" | "high_risk" | "not_scored") | null;
            /** Candidate */
            candidate: boolean;
            /** Display Name */
            display_name: string;
            /** Parcel Id */
            parcel_id: string;
            /** Rank */
            rank?: number | null;
            /** Score */
            score: number | null;
        };
        /**
         * ParcelReport
         * @description Everything the report panel needs: the header and the engine's analysis.
         */
        ParcelReport: {
            /** @description None when the lot is not a candidate */
            analysis: components["schemas"]["SiteAnalysis"] | null;
            /** @description None when the facts behind the analysis are not stored */
            freshness?: components["schemas"]["Freshness"] | null;
            parcel: components["schemas"]["ParcelSummary"];
        };
        /**
         * ParcelSummary
         * @description One row in the results list, one feature on the map, the report header.
         *
         *     Facts come from SiteContext, judgments are copied from the engine's SiteAnalysis; the API
         *     computes nothing here.
         */
        ParcelSummary: {
            /** Address */
            address: string | null;
            /**
             * Assembly Id
             * @description Lots that work together
             */
            assembly_id?: string | null;
            /** Assessed Land */
            assessed_land: number | null;
            /**
             * Band
             * @description None when there is no analysis
             */
            band?: ("fast_track" | "feasible_with_conditions" | "high_risk" | "not_scored") | null;
            /**
             * Block Lot
             * @description Dashed city block-lot, e.g. 55-A-137
             */
            block_lot: string | null;
            /**
             * Candidate
             * @description False = not a development candidate (outline only)
             */
            candidate: boolean;
            /**
             * Centroid
             * @description [lon, lat], EPSG:4326
             */
            centroid: [
                number,
                number
            ];
            /** Combined Sewershed */
            combined_sewershed?: boolean | null;
            /** Current Use */
            current_use: string;
            /** Display Name */
            display_name: string;
            /**
             * Flood Share
             * @description FEMA zones, excluding X500
             */
            flood_share?: number | null;
            /**
             * Has Structure
             * @default false
             */
            has_structure: boolean;
            /**
             * Illustrative
             * @description True for generated mock parcels
             */
            illustrative: boolean;
            /** Landslide Share */
            landslide_share?: number | null;
            lead_option?: components["schemas"]["LeadOption"] | null;
            /** Lot Area Sqft */
            lot_area_sqft: number;
            max_land_price?: components["schemas"]["Range"] | null;
            months_to_permit?: components["schemas"]["Range"] | null;
            /** Municipality */
            municipality: string;
            /** Neighborhood */
            neighborhood: string | null;
            /**
             * Owner Type
             * @enum {string}
             */
            owner_type: "private" | "city" | "land_bank" | "ura" | "other_public";
            /**
             * Parcel Id
             * @description Canonical 16-character county ID
             */
            parcel_id: string;
            /**
             * Programs
             * @description Every building type the engine tested
             */
            programs?: components["schemas"]["ProgramFit"][];
            /** Score */
            score?: number | null;
            site_cost_premium?: components["schemas"]["CostRange"] | null;
            /** Steep Slope Share */
            steep_slope_share?: number | null;
            /**
             * Tax Lien Usd
             * @default 0
             */
            tax_lien_usd: number;
            /** Top Flag */
            top_flag?: string | null;
            /** Top Flag Severity */
            top_flag_severity?: ("high" | "medium" | "low" | "unknown") | null;
            /** Transit Distance Ft */
            transit_distance_ft?: number | null;
            /** Undermined Share */
            undermined_share?: number | null;
            /**
             * Zoning
             * @description Zoning district codes on the lot
             */
            zoning: string[];
        };
        /** ParseRequest */
        ParseRequest: {
            current_filters?: components["schemas"]["SearchFilters"] | null;
            /** Text */
            text: string;
        };
        /** ParseResult */
        ParseResult: {
            /** Chips */
            chips: components["schemas"]["FilterChip"][];
            /**
             * Detected
             * @default description
             * @enum {string}
             */
            detected: "parcel_id" | "address" | "description";
            filters: components["schemas"]["SearchFilters"];
            /** Not Understood */
            not_understood?: string[];
            /**
             * Parser
             * @description rules = basic search (AI unavailable)
             * @enum {string}
             */
            parser: "ai" | "rules";
            /** Readings */
            readings?: components["schemas"]["Reading"][];
        };
        /** ProductFilter */
        ProductFilter: {
            /**
             * Type
             * @description None = any building type
             */
            type?: ("single_family" | "duplex" | "triplex" | "townhome" | "walkup") | null;
            /**
             * Units
             * @description At least this many
             */
            units?: number | null;
        };
        /** ProgramEvaluation */
        ProgramEvaluation: {
            approval_months: components["schemas"]["Range"] | null;
            approval_prob: components["schemas"]["Range"] | null;
            /** Checks */
            checks: components["schemas"]["CheckResult"][];
            /** Chosen As */
            chosen_as: ("by_right" | "with_relief") | null;
            /** Gfa Sqft */
            gfa_sqft: number;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "by_right" | "needs_approval" | "rejected";
            /**
             * Product Type
             * @enum {string}
             */
            product_type: "single_family" | "duplex" | "triplex" | "townhome" | "walkup";
            /** Representative */
            representative: boolean;
            /** Units */
            units: number;
        };
        /**
         * ProgramFit
         * @description One building type the engine tested on the lot (`rule_checks.programs`).
         */
        ProgramFit: {
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "by_right" | "needs_approval" | "rejected";
            /**
             * Product Type
             * @enum {string}
             */
            product_type: "single_family" | "duplex" | "triplex" | "townhome" | "walkup";
            /**
             * Relief Types
             * @description Approvals that fix the failing rules
             */
            relief_types: string[];
            /** Units */
            units: number;
        };
        /** ProgramOption */
        ProgramOption: {
            approval_prob: components["schemas"]["Range"];
            /** Entitlement Basis */
            entitlement_basis: string[];
            /** Gfa Sqft */
            gfa_sqft: number;
            /**
             * Label
             * @enum {string}
             */
            label: "by_right" | "with_relief";
            margin: components["schemas"]["Range"];
            max_land_price: components["schemas"]["Range"];
            months: components["schemas"]["Range"];
            /**
             * Product Type
             * @enum {string}
             */
            product_type: "single_family" | "duplex" | "triplex" | "townhome" | "walkup";
            /** Relief */
            relief: string[];
            /** Revenue Basis */
            revenue_basis: string;
            score: components["schemas"]["Range"];
            site_cost_premium?: components["schemas"]["Range"] | null;
            /** Unit Sqft */
            unit_sqft: number;
            /** Units */
            units: number;
        };
        /**
         * Range
         * @description Every estimate ships as a range: 10th, 50th and 90th percentile of the simulation.
         */
        Range: {
            /** P10 */
            p10: number;
            /** P50 */
            p50: number;
            /** P90 */
            p90: number;
        };
        /**
         * Reading
         * @description How one phrase of the user's text was read. Shown in the AI search preview.
         */
        Reading: {
            /** Interpreted As */
            interpreted_as: string;
            /** Phrase */
            phrase: string;
        };
        /**
         * RuleChecks
         * @description Every building type tested on this lot, rule by rule ("why this score").
         */
        RuleChecks: {
            /** District */
            district: string;
            /** Not Checked */
            not_checked: components["schemas"]["NotChecked"][];
            /** Odds Note */
            odds_note: string;
            /** Programs */
            programs: components["schemas"]["ProgramEvaluation"][];
            /**
             * Scenario
             * @enum {string}
             */
            scenario: "strict" | "contextual";
            /** Site Checks */
            site_checks: components["schemas"]["SiteCheck"][];
            /** Uncovered Districts */
            uncovered_districts: string[];
        };
        /** RulesSummary */
        RulesSummary: {
            /** Confidence */
            confidence: ("high" | "medium" | "low") | null;
            lot_dimensions_ft: components["schemas"]["LotDimensions"] | null;
            /** Neighbors Built */
            neighbors_built: boolean | null;
            /** Scenario */
            scenario: ("strict" | "contextual") | null;
        };
        /**
         * ScoreComponent
         * @description One bar of "Where the score comes from". Points of all components sum to the score.
         */
        ScoreComponent: {
            /**
             * Key
             * @enum {string}
             */
            key: "approval_path" | "site_cost" | "land_headroom";
            /** Label */
            label: string;
            /** Max Points */
            max_points: number;
            /** Note */
            note: string;
            /** Points */
            points: number;
        };
        /**
         * ScoreItem
         * @description Counterfactual: points the score would regain without this driver.
         */
        ScoreItem: {
            /**
             * Component
             * @enum {string}
             */
            component: "approval_path" | "site_cost" | "land_headroom";
            /** Driver Flag Id */
            driver_flag_id: string;
            /** Points Lost */
            points_lost: number;
        };
        /**
         * SearchFilters
         * @description The single filter state shared by the manual controls, the chips and AI search.
         */
        SearchFilters: {
            /**
             * Approval Paths
             * @description Empty = any
             */
            approval_paths?: ("by_right" | "administrative" | "special_exception" | "variance" | "rezoning" | "not_allowed")[];
            /**
             * Areas
             * @description Pittsburgh neighborhood names, canonical spelling
             */
            areas?: string[];
            /**
             * Bands
             * @description Empty = all bands
             */
            bands?: ("fast_track" | "feasible_with_conditions" | "high_risk" | "not_scored")[];
            /** Exclude Constraints */
            exclude_constraints?: ("undermined" | "flood_zone" | "landslide" | "combined_sewer" | "steep_slope")[];
            /**
             * Include Unknowns
             * @default true
             */
            include_unknowns: boolean;
            /** Lot Max Sqft */
            lot_max_sqft?: number | null;
            /** Lot Min Sqft */
            lot_min_sqft?: number | null;
            /**
             * Max Land Price
             * @description USD, land only
             */
            max_land_price?: number | null;
            /** Max Months To Permit */
            max_months_to_permit?: number | null;
            /**
             * Max Site Cost Premium
             * @description USD
             */
            max_site_cost_premium?: number | null;
            /**
             * Max Steep Slope Pct
             * @description Max percent of lot at 25%+ slope
             */
            max_steep_slope_pct?: number | null;
            /** Min Margin Pct */
            min_margin_pct?: number | null;
            /** Min Score */
            min_score?: number | null;
            /** Near */
            near?: components["schemas"]["NearFilter"][];
            /** Owner Types */
            owner_types?: ("private" | "city" | "land_bank" | "ura" | "other_public")[];
            product?: components["schemas"]["ProductFilter"] | null;
            /**
             * Show Assemblies
             * @default false
             */
            show_assemblies: boolean;
            /**
             * Show Near Misses
             * @default false
             */
            show_near_misses: boolean;
            /**
             * Sort
             * @default score_desc
             * @enum {string}
             */
            sort: "score_desc" | "headroom_desc" | "fastest" | "cheapest";
            /**
             * Tax Delinquent Only
             * @default false
             */
            tax_delinquent_only: boolean;
            /**
             * Vacant Only
             * @default false
             */
            vacant_only: boolean;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Assemblies */
            assemblies?: components["schemas"]["Assembly"][];
            /** Chips */
            chips: components["schemas"]["FilterChip"][];
            filters: components["schemas"]["SearchFilters"];
            /** Near Misses */
            near_misses?: components["schemas"]["NearMiss"][];
            /**
             * Not Applied
             * @description Filters the data can't answer yet; ignored
             */
            not_applied?: components["schemas"]["FilterChip"][];
            /** Results */
            results: components["schemas"]["SearchResult"][];
            suggestion?: components["schemas"]["Suggestion"] | null;
            /** Total */
            total: number;
        };
        /** SearchResult */
        SearchResult: {
            /** @description The program that matched the product filter */
            fit: components["schemas"]["ProgramFit"] | null;
            parcel: components["schemas"]["ParcelSummary"];
            /** Rank */
            rank: number;
        };
        /** SiteAnalysis */
        SiteAnalysis: {
            /** Assumptions */
            assumptions: components["schemas"]["Assumption"][];
            /** Cleared */
            cleared: string[];
            /** Flags */
            flags: components["schemas"]["Flag"][];
            metrics: components["schemas"]["Metrics"] | null;
            narrative: components["schemas"]["Narrative"];
            /** Next Steps */
            next_steps: components["schemas"]["Step"][];
            /** Options */
            options: components["schemas"]["ProgramOption"][];
            rule_checks?: components["schemas"]["RuleChecks"] | null;
            rules: components["schemas"]["RulesSummary"];
            /** Score Breakdown */
            score_breakdown: components["schemas"]["ScoreItem"][];
            verdict: components["schemas"]["Verdict"];
            versions: components["schemas"]["Versions"];
        };
        /**
         * SiteCheck
         * @description Overlay rules that apply to the site whatever is built.
         */
        SiteCheck: {
            /** Check Id */
            check_id: string;
            /** Label */
            label: string;
            /** Note */
            note: string | null;
            /** Section */
            section: string;
            /**
             * Status
             * @enum {string}
             */
            status: "applies" | "clear" | "unknown";
        };
        /** Step */
        Step: {
            /** Action */
            action: string;
            /** Cost Usd */
            cost_usd: [
                number,
                number
            ];
            /** Flag Ids */
            flag_ids: string[];
            /** Order */
            order: number;
            /** Who */
            who: string;
            /** Why */
            why: string;
        };
        /**
         * Suggestion
         * @description When nothing matches: the filter whose removal brings back the most sites.
         */
        Suggestion: {
            remove: components["schemas"]["FilterChip"];
            /** Would Return */
            would_return: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Verdict */
        Verdict: {
            /**
             * Band
             * @enum {string}
             */
            band: "fast_track" | "feasible_with_conditions" | "high_risk" | "not_scored";
            /** Components */
            components: components["schemas"]["ScoreComponent"][];
            /** Headline */
            headline: string;
            /** Land Risk */
            land_risk: string | null;
            /** Score */
            score: number | null;
            score_range: components["schemas"]["Range"] | null;
        };
        /** Versions */
        Versions: {
            /** Data As Of */
            data_as_of: string | null;
            /** Engine */
            engine: string;
            /** Ruleset */
            ruleset: string;
            /** Schema */
            schema: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    evidence_api_evidence__evidence_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    examples_api_examples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Examples"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    lookup_parcels_api_lookup_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LookupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    map_features_api_map_features_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapFeatureCollection"];
                };
            };
        };
    };
    map_parcels_api_map_parcels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParcelFeatureCollection"];
                };
            };
        };
    };
    neighborhoods_api_neighborhoods_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Neighborhood"][];
                };
            };
        };
    };
    parcel_report_api_parcels__parcel_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parcel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParcelReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_parcels_api_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchFilters"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_text_api_search_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
