/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence */
        get: operations["evidence_api_evidence__evidence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parcels/{parcel_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Parcel Analysis
         * @description Screening analysis for one parcel, by county parcel ID (dashed or compact).
         *
         *     `product` and `units` are passed to the engine once it exists; the mock ignores them.
         */
        get: operations["parcel_analysis_api_parcels__parcel_id__analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisMeta */
        AnalysisMeta: {
            /**
             * Contract Version
             * @default 0.1.0
             */
            contract_version: string;
            /**
             * Data Refreshed
             * Format: date
             */
            data_refreshed: string;
            /** Engine Version */
            engine_version: string;
            /**
             * Illustrative
             * @default false
             */
            illustrative: boolean;
            /** Rules Version */
            rules_version: string;
        };
        /** Assumption */
        Assumption: {
            /**
             * Editable
             * @default true
             */
            editable: boolean;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Source Label */
            source_label: string;
            /** Value */
            value: components["schemas"]["Range"] | number | string;
        };
        /** Case */
        Case: {
            /** Case Id */
            case_id: string;
            /** Months To Decision */
            months_to_decision?: number | null;
            /** Neighborhood */
            neighborhood: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "granted" | "denied" | "withdrawn" | "pending";
            /** Request */
            request: string;
            /** Source Url */
            source_url?: string | null;
        };
        /** ClearedCheck */
        ClearedCheck: {
            /** Label */
            label: string;
            source?: components["schemas"]["SourceRef"] | null;
        };
        /** CodeReference */
        CodeReference: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Section */
            section: string;
            /** Summary */
            summary: string;
            /** Url */
            url?: string | null;
        };
        /** Evidence */
        Evidence: {
            /**
             * Ai Extracted
             * @default false
             */
            ai_extracted: boolean;
            /** Applies To */
            applies_to: string;
            /** Cases */
            cases?: components["schemas"]["Case"][];
            code?: components["schemas"]["CodeReference"] | null;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Confidence Note */
            confidence_note: string;
            /** How To Resolve */
            how_to_resolve: string;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "zoning_relief" | "physical" | "infrastructure" | "market";
            /** Median Months */
            median_months?: number | null;
            /** Precedent Granted */
            precedent_granted?: number | null;
            /** Precedent Total */
            precedent_total?: number | null;
            /** Title */
            title: string;
        };
        /** Finding */
        Finding: {
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Confidence Note */
            confidence_note?: string | null;
            /** Detail */
            detail: string;
            /** Evidence Id */
            evidence_id?: string | null;
            /** Id */
            id: string;
            impact_cost?: components["schemas"]["Range"] | null;
            /** Impact Label */
            impact_label: string;
            impact_months?: components["schemas"]["Range"] | null;
            /** Resolved By Step */
            resolved_by_step?: number | null;
            /**
             * Severity
             * @enum {string}
             */
            severity: "deal_risk" | "caution" | "unknown";
            /** Sources */
            sources: components["schemas"]["SourceRef"][];
            /** Title */
            title: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeadlineNumbers */
        HeadlineNumbers: {
            /**
             * Approval Path
             * @enum {string}
             */
            approval_path: "by_right" | "special_exception" | "variance" | "rezoning" | "not_allowed";
            /** Approval Summary */
            approval_summary: string;
            /** Comps Count */
            comps_count: number;
            /** Comps Radius Mi */
            comps_radius_mi: number;
            /** Comps Window Months */
            comps_window_months: number;
            /** Listed Price */
            listed_price?: number | null;
            max_land_price: components["schemas"]["Range"];
            months_to_permit_ready: components["schemas"]["Range"];
            site_cost_premium: components["schemas"]["Range"];
            /** Site Cost Summary */
            site_cost_summary: string;
            /** Target Margin Pct */
            target_margin_pct: number;
        };
        /** Health */
        Health: {
            /** Illustrative */
            illustrative: boolean;
            /**
             * Site Source
             * @enum {string}
             */
            site_source: "mock" | "pipeline";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            versions: components["schemas"]["Versions"];
        };
        /** NextStep */
        NextStep: {
            /** @description low=high=0 means free */
            cost: components["schemas"]["Range"];
            /** Duration Label */
            duration_label: string;
            /** Order */
            order: number;
            /** Title */
            title: string;
            /** Who */
            who: string;
            /** Why */
            why: string;
        };
        /**
         * ParcelSummary
         * @description One row in the results list, one feature on the map, one inspector card.
         */
        ParcelSummary: {
            /** Address */
            address?: string | null;
            /** Assessed Value */
            assessed_value?: number | null;
            /**
             * Band
             * @enum {string}
             */
            band: "fast_track" | "conditions" | "high_risk" | "unknown";
            best_program?: components["schemas"]["ProgramOption"] | null;
            /**
             * Centroid
             * @description [lon, lat]
             */
            centroid: [
                number,
                number
            ];
            /** Current Use */
            current_use: string;
            /** Display Name */
            display_name: string;
            /** Listed Price */
            listed_price?: number | null;
            /** Lot Area Sqft */
            lot_area_sqft: number;
            max_land_price?: components["schemas"]["Range"] | null;
            /** Neighborhood */
            neighborhood: string;
            /**
             * Owner Type
             * @enum {string}
             */
            owner_type: "land_bank" | "ura" | "city" | "private" | "other_public";
            /** Parcel Id */
            parcel_id: string;
            /** Rank */
            rank?: number | null;
            /** Score */
            score?: number | null;
            /** Top Risk */
            top_risk?: string | null;
            /** Top Risk Severity */
            top_risk_severity?: ("deal_risk" | "caution" | "unknown") | null;
            /** Zoning District */
            zoning_district: string;
        };
        /** ProgramOption */
        ProgramOption: {
            /**
             * Approval Path
             * @enum {string}
             */
            approval_path: "by_right" | "special_exception" | "variance" | "rezoning" | "not_allowed";
            /**
             * Code Basis
             * @description e.g. 'By-right under Title Nine as of Sep 2026 · § 903.03'
             */
            code_basis?: string | null;
            /** Evidence Id */
            evidence_id?: string | null;
            margin_pct: components["schemas"]["Range"];
            months_to_permit_ready: components["schemas"]["Range"];
            /** Precedent Granted */
            precedent_granted?: number | null;
            /** Precedent Total */
            precedent_total?: number | null;
            /**
             * Product
             * @enum {string}
             */
            product: "adu" | "duplex" | "townhomes" | "walkup";
            /**
             * Relief
             * @description Code sections needing relief, e.g. '§ 911.02'
             */
            relief?: string[];
            /** Sqft Each */
            sqft_each?: number | null;
            /**
             * Tenure
             * @default for_sale
             * @enum {string}
             */
            tenure: "for_sale" | "rental";
            /** Units */
            units: number;
        };
        /**
         * Range
         * @description Every estimate is a range, never a point.
         */
        Range: {
            /** High */
            high: number;
            /** Low */
            low: number;
            /**
             * Unit
             * @enum {string}
             */
            unit: "usd" | "usd_per_sqft" | "pct" | "months" | "sqft" | "points";
        };
        /** ScoreComponent */
        ScoreComponent: {
            /**
             * Key
             * @description e.g. approval_path, site_cost, land_headroom
             */
            key: string;
            /** Label */
            label: string;
            /** Max Points */
            max_points: number;
            /** Note */
            note: string;
            /** Points */
            points: number;
        };
        /** SiteAnalysis */
        SiteAnalysis: {
            /** Assumptions */
            assumptions: components["schemas"]["Assumption"][];
            best_by_right?: components["schemas"]["ProgramOption"] | null;
            best_with_approvals?: components["schemas"]["ProgramOption"] | null;
            /** Cleared */
            cleared: components["schemas"]["ClearedCheck"][];
            /**
             * Findings
             * @description Ordered worst first
             */
            findings: components["schemas"]["Finding"][];
            headline_numbers: components["schemas"]["HeadlineNumbers"];
            meta: components["schemas"]["AnalysisMeta"];
            /**
             * Next Steps
             * @description Ordered cheapest deal-killers first
             */
            next_steps: components["schemas"]["NextStep"][];
            parcel: components["schemas"]["ParcelSummary"];
            /** Score Breakdown */
            score_breakdown: components["schemas"]["ScoreComponent"][];
            verdict: components["schemas"]["Verdict"];
        };
        /**
         * SourceRef
         * @description Where a fact came from. Shown on every finding.
         */
        SourceRef: {
            /** As Of */
            as_of?: string | null;
            /**
             * Dataset
             * @description Dataset or publisher, e.g. 'WPRDC'
             */
            dataset: string;
            /**
             * Label
             * @description Short display label, e.g. 'City steep slopes 25%+'
             */
            label: string;
            /** Url */
            url?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Verdict */
        Verdict: {
            /**
             * Band
             * @enum {string}
             */
            band: "fast_track" | "conditions" | "high_risk" | "unknown";
            /**
             * Headline
             * @description One or two sentences. Screening language only, never 'approved' or 'compliant'.
             */
            headline: string;
            /** Score */
            score?: number | null;
            score_range?: components["schemas"]["Range"] | null;
        };
        /**
         * Versions
         * @description What produced the data being served. Every SiteAnalysis stamps the same versions.
         */
        Versions: {
            /**
             * Data As Of
             * Format: date
             */
            data_as_of: string;
            /** Engine */
            engine: string;
            /** Ruleset */
            ruleset: string;
            /** Schema Version */
            schema_version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    evidence_api_evidence__evidence_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    parcel_analysis_api_parcels__parcel_id__analysis_get: {
        parameters: {
            query?: {
                product?: ("adu" | "duplex" | "townhomes" | "walkup") | null;
                units?: number | null;
            };
            header?: never;
            path: {
                parcel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteAnalysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
